# Generated by Django 3.0.2 on 2020-06-25 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=1500)),
                ('status', models.CharField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, upload_to='profile_avatars/')),
                ('contacts', models.TextField(blank=True, max_length=1500)),
                ('blogs', models.TextField(default='blog name', max_length=1500)),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
