# Generated by Django 3.0.2 on 2020-06-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20200626_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blogs',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='readers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='topics',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rooms_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
