# Generated by Django 3.0.2 on 2020-07-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20200627_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='profile',
            name='subs_profiles',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
