# Generated by Django 3.0.2 on 2020-07-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20200713_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='blackout',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
