# Generated by Django 3.0.2 on 2020-07-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20200713_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='quote',
        ),
        migrations.AddField(
            model_name='settings',
            name='unsplash_background',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='setting_covers/'),
        ),
    ]
