# Generated by Django 3.0.4 on 2020-07-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20200714_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='colors',
            field=models.CharField(default='|#FFFFFF|#323232|', max_length=17),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(default='', max_length=500),
        ),
    ]
