# Generated by Django 3.0.4 on 2020-08-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20200727_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rooms_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='topics',
        ),
    ]
