# Generated by Django 3.0.4 on 2020-08-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20200801_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='http://', upload_to='profile_avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Описание профиля', max_length=3000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(max_length=500),
        ),
    ]
