# Generated by Django 3.0.4 on 2020-08-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20200801_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
