# Generated by Django 3.0.4 on 2020-08-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_profile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/media/profile_avatars/default_avatar.png', upload_to='profile_avatars/'),
        ),
    ]
