# Generated by Django 3.0.4 on 2020-08-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20200805_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='blur',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
