# Generated by Django 3.0.4 on 2020-08-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_auto_20200811_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='colors',
            field=models.CharField(default='|#FFFFFF|', max_length=17),
        ),
    ]
