# Generated by Django 3.1 on 2020-08-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_auto_20200811_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='colors',
        ),
    ]
