# Generated by Django 3.1 on 2020-08-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_remove_settings_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='background',
            field=models.ImageField(blank=True, default='', null=True, upload_to='setting_covers/'),
        ),
    ]
