# Generated by Django 3.0.2 on 2020-06-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='video_url',
        ),
        migrations.AddField(
            model_name='room',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
