# Generated by Django 3.0.2 on 2020-05-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200516_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='note_color',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=7000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
