# Generated by Django 3.0.2 on 2020-05-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200522_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_color',
            field=models.CharField(default='', max_length=7),
        ),
    ]
