# Generated by Django 3.0.2 on 2020-06-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_post_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='note_color',
            field=models.CharField(default='white', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_color',
            field=models.CharField(default='#212121', max_length=7),
        ),
    ]
