# Generated by Django 3.0.2 on 2020-06-29 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200625_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=1000)),
                ('text', models.TextField(max_length=10000)),
                ('video_url', models.TextField(blank=True, default='', max_length=300)),
                ('blog_name', models.CharField(default='', max_length=200)),
                ('note_color', models.CharField(default='white', max_length=7)),
                ('text_color', models.CharField(default='#212121', max_length=7)),
                ('image0', models.ImageField(blank=True, upload_to='post_images/')),
                ('image1', models.ImageField(blank=True, upload_to='post_images/')),
                ('image2', models.ImageField(blank=True, upload_to='post_images/')),
                ('image3', models.ImageField(blank=True, upload_to='post_images/')),
                ('image4', models.ImageField(blank=True, upload_to='post_images/')),
                ('image5', models.ImageField(blank=True, upload_to='post_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='username',
        ),
        migrations.RemoveField(
            model_name='document',
            name='views',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='username',
        ),
        migrations.RemoveField(
            model_name='image',
            name='views',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='community_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='note_color',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='document',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='news.Post'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo_posts/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='news.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AddField(
            model_name='note',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='note', to='news.Post'),
        ),
    ]
