# Generated by Django 3.0.2 on 2020-06-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200629_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.RemoveField(
            model_name='note',
            name='image0',
        ),
        migrations.RemoveField(
            model_name='note',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='note',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='note',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='note',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='note',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='news.Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='news.Post'),
        ),
    ]
