# Generated by Django 3.0.2 on 2020-07-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20200630_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='note_color',
            field=models.CharField(blank=True, default='white', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_color',
            field=models.CharField(blank=True, default='#212121', max_length=7),
        ),
    ]
