# Generated by Django 3.0.2 on 2020-07-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20200704_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(default='ru', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='marks',
            field=models.TextField(blank=True, default='|', max_length=500),
        ),
    ]
