# Generated by Django 3.0.4 on 2020-08-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20200719_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.TextField(default='|', max_length=5000),
        ),
    ]
