# Generated by Django 3.1 on 2020-08-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20200805_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='username',
            field=models.CharField(default='TestUserName', max_length=100),
            preserve_default=False,
        ),
    ]
